apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasp-dev-db-opensaas-06def77781
  labels:
    app: wasp-dev-db-opensaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasp-dev-db-opensaas
  template:
    metadata:
      labels:
        app: wasp-dev-db-opensaas
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "postgresWaspDevPass"
            - name: POSTGRES_USER
              value: "postgresWaspDevUser"
            - name: POSTGRES_DB
              value: "OpenSaaS-06def77781"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: wasp-dev-db-opensaas-06def77781-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wasp-dev-db-opensaas-06def77781-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wasp-dev-db-opensaas-06def77781
  labels:
    app: wasp-dev-db-opensaas
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: wasp-dev-db-opensaas
  type: ClusterIP

