kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: opensaas-buildconfig 
  namespace: florian-ns
spec:
  output:
    to:
      kind: DockerImage
      name: "quay.io/neutron-it/opensaas:latest"
    pushSecret:
      name: florian-even-pull-secret
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  source:
    type: Git
    git:
      uri: "git@github.com:neutron-IT-organization/open-saas-openshift.git"
    contextDir: /
    sourceSecret:
      name: github-deploy-key

