FROM node:18.18.0-alpine3.17 AS server-production
RUN apk add --no-cache python3
ENV NODE_ENV production
WORKDIR /app
COPY . /app/
EXPOSE 3001
WORKDIR /app/.wasp/build/server
ENTRYPOINT ["npm", "run", "start-production"]



