kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: opensaas-frontend
  namespace: test
spec:
  output:
    to:
      kind: DockerImage
      name: 'quay.io/florian_even/opensaas-frontend:latest'
    pushSecret:
      name: florian-pull-secret
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile-frontend
  serviceAccount: builder
  source:
    type: Git
    git:
      uri: 'git@github.com:neutron-IT-organization/open-saas-openshift.git'
    contextDir: /app
    sourceSecret:
      name: github-deploy-key


