apiVersion: v1
kind: Secret
metadata:
  name: florian-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJabXh2Y21saGJsOWxkbVZ1T25SUVNqZ3lNVzFvVldsTlNWaDVWbE5QUlhseVMwcHhVaTgyYzBSNWVGTXZaQzlMTlRGMWNIaGhZVFZWWkdvNFZHbE5NR3h0YjJ4NE5XOVVhbEZLVFhVPSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
